### PR TITLE
Owner names of CNAMEs MUST always start with underscore

### LINKED ISSUE #138: Inconsistency on guidance of underscore before a token
Our current guidance (from #105) on "When placed in a domain name, the token MUST NOT start with an underscore to avoid attacks where tokens are maliciously used as a scope label." is inconsistent with parts of the doc where we do use an underscore before a token.

Also https://datatracker.ietf.org/doc/html/draft-ietf-acme-scoped-dns-challenges-00 does do this.  

Also remove the:
> (TODO / DISCUSS: should we remove the underscore in-front of identifier-token per the guidance above?)

I'm almost wonder if we need to remove the "When placed in a domain name, the token MUST NOT start with an underscore to avoid attacks where tokens are maliciously used as a scope label."  or change it to be something different.

This may actually warrant some discussion on the list or in the session?

### PR DESCRIPTION
**Pull request by enygren**
To address the concerns in #138, be clear that the owner names of CNAMEs MUST always start with an underscore.

It would be worth reviewing this again to see if I missed any. One thing this does not address is the concern that there could be ambiguity that dkg raised for if a "random" token was also a challenge label.  I'm not sure how we address this?

Resolves #138

### CODE REVIEW

**Comment by shuque** [comment]
This PR looks good to me.

I'm not sure I see what the ambiguity is. So, yes, we should discuss on list, and specifically get dkg to review.

I suggest we merge this, push out the next revision before the IETF121 draft cutoff, and have a discussion subsequently on list or at IETF121.

**Comment by shuque** [comment]
I was looking for a reference from the CABforum where this requirement is stated. I think it is this section from their Baseline Requirements doc:

3.2.2.4.7 DNS Change
Confirming the Applicant’s control over the FQDN by confirming the presence of a Random Value or Request Token for either in a DNS CNAME, TXT or CAA record for either 1) an Authorization Domain Name; or 2) an Authorization Domain Name that is prefixed with a Domain Label that begins with an underscore character.

**Comment by ShivanKaul** [comment]
What if we didn't merge this but instead just discussed it live during the DNSOP meeting? @moonshiner

**Comment by shuque** [comment]
@ShivanKaul - discussing at DNSOP is also a reasonable option.

At the end of the day, I think we'll need to reconcile this draft with the relevant CAB forum rules, as those rules are how the WebPKI works.

So if there is a compelling reason against the underscore rule for the owner name, we'll need to state what that is and then try to persuade the CAB forum. If there isn't or if there is a compelling reason to have the rule (to avoid collisions with legitimate hostnames), then I think we should add something like this PR.

**Comment by moonshiner** [comment]
I'm good with discussing during DNSOP

**Comment by paulwouters** [comment]
I find merge, then talk works better for dnsop :P

**Comment by moonshiner** [comment]
Someone needs to do the magic conflict resolving.

**Pull request merged**
