### PR TITLE
New 'Common Pitfalls' section to highlight operational issues

### PR DESCRIPTION
**Pull request by shuque**
New 'Common Pitfalls' section early in the doc that highlights operational issues with colliding TXT records at a common domain name. This discussion was previously buried in the appendix.

Also a few small language tweaks to the abstract and intro to make it more readable.

### CODE REVIEW

**Comment by moonshiner** [comment]
my only comment would be "methods, not avenues" but I like this. Thanks!

**Comment by shuque** [comment]
I think I already changed that (I did not like "avenues" either). See if I
missed anything please ..

**Comment by moonshiner** [comment]
You Did and I read it wrong!  thank you sir

**Review by ShivanKaul — APPROVED** [review]
Love it!

**Pull request merged**
