### PR TITLE
Restructure Recommendations and clarify CNAME sections

### PR DESCRIPTION
**Pull request by enygren**
* Reorders some sections for clarity or better grouping
* Better specifies the types of "CNAME validation"
* Factors out the different "CNAME" sections that were unrelated
* Replaces "host name" with "hostname" for consistency
* Mention some risks of #23 (predictable QNAME)

Addresses  #127

Note that this has lots of re-ordering of sections which makes this fairly large diff.

### CODE REVIEW

**Comment by moonshiner** [comment]
I see you use "Validation Record" but not the definition is "Validation record" and I see "validation record" in other places. can you look?

**Comment by enygren** [comment]
I accidentally included the "Validation Record" consistency in #135.
Note that #135 is based off of this PR, so we'll want to merge this PR first before reviewing that one.
I figured I'd submit both since we're running tight on time.
(I can always close and redo #135 if that would be easier.)

**Review by moonshiner — APPROVED** [review]
"The presence of a validation record with a predictable domain name (either as a TXT record for the exact domain name where control is being validated or with a well-known label) can allow attackers to enumerate utilized set of Application Service Providers."

Could this in Security Considerations? good either way

**Comment by enygren** [comment]
> Could this in Security Considerations? good either way

I'm fine either way as well.

**Review by shuque — APPROVED** [review]
Looks good.

**Review by ShivanKaul — APPROVED** [review]

**Pull request merged**
